// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"WebService/dal/dao"
	"WebService/dal/dao_impl"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitService() (*Component, error) {
	userDaoImpl := &dao_impl.UserDaoImpl{}
	commonService := CommonService{
		userDao: userDaoImpl,
	}
	component := &Component{
		CommonService: commonService,
	}
	return component, nil
}

// wire.go:

var serviceSet = wire.NewSet(wire.Struct(new(CommonService), "*"))

var daoSet = wire.NewSet(wire.Struct(new(dao_impl.UserDaoImpl), "*"), wire.Bind(new(dao.UserDao), new(*dao_impl.UserDaoImpl)))

type Component struct {
	CommonService
}
